---

- name: get-api project
  hosts: dev
  remote_user: vagrant

  roles:
    - role: gantsign.oh-my-zsh
      users:
        - username: vagrant
    - mysql
    - role: php7_1
      php_dev: yes
    - role: apache2
      become: yes
      apache_vhosts:
        # Additional optional properties: 'serveradmin, serveralias, extra_parameters'.
        - servername: "get-api.local"
          documentroot: "/var/www/get-api.local/public"
    - common
    - role: symfony4
      app_dir: /var/www/get-api.local

...
