---

- name: get project
  hosts: dev
  remote_user: vagrant

  roles:
    - role: gantsign.oh-my-zsh
      users:
        - username: vagrant
    - mysql
    - role: php7_1
      php_dev: yes
    - role: apache2
      become: yes
      apache_vhosts:
        - {servername: "get.api", documentroot: "/var/www/get.api/public"}
        - {servername: "get.web", documentroot: "/var/www/get.web/public"}
    - common
    - role: symfony4
      app_dir: /var/www/get.api

...
